# Generated by Django 4.1 on 2022-11-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_id', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('deliveryDate', models.DateTimeField()),
                ('price', models.IntegerField(default=100)),
                ('is_published', models.BooleanField(default=True)),
                ('own', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.owner')),
                ('taskType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.category')),
                ('universityTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.university')),
            ],
        ),
    ]
