# Generated by Django 4.1 on 2022-11-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='own',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange.owner', verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
