# Generated by Django 4.1 on 2022-11-07 18:55

from django.db import migrations, models
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_task_own'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(default=1, upload_to=exchange.models.user_path),
            preserve_default=False,
        ),
    ]
