# Generated by Django 4.1 on 2022-11-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='image',
            new_name='files',
        ),
    ]
