# Generated by Django 4.1 on 2022-11-07 19:08

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_rename_image_task_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filesUrl', models.FileField(upload_to=exchange.models.user_path)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.files'),
        ),
    ]
