# Generated by Django 4.1 on 2022-11-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_files_alter_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filesUrl',
            field=models.FileField(upload_to='data'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default='No Title', max_length=255),
        ),
    ]
