# Generated by Django 4.1 on 2022-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_files_filesurl_alter_files_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filesUrl',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='data'),
        ),
    ]
