# Generated by Django 4.1 on 2022-11-07 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_files_filesurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='files',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='exchange.files'),
        ),
    ]
