# Generated by Django 4.1 on 2022-11-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_task_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filesUrl',
            field=models.FileField(max_length=255, null=True, upload_to='data'),
        ),
    ]
